version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
